install: pip install -U coveralls .

language: python

python:
    - 3.8
    - 3.7
    - 3.6
    - 3.5
    - 3.4
    - 3.3

script:
    - coverage run --source="yamicache" -p -m py.test
    - coverage combine
    - coverage report -m


after_success:
    - coveralls
